doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/User/Entity'
                prefix: 'App\Domain\User\Entity'
                alias: User
            Gym:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Gym/Entity'
                prefix: 'App\Domain\Gym\Entity'
                alias: Gym
            PersonalTrainer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/PersonalTrainer/Entity'
                prefix: 'App\Domain\PersonalTrainer\Entity'
                alias: PersonalTrainer
            Membership:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Membership/Entity'
                prefix: 'App\Domain\Membership\Entity'
                alias: Membership
            Workout:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Workout/Entity'
                prefix: 'App\Domain\Workout\Entity'
                alias: Workout
            Medical:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Medical/Entity'
                prefix: 'App\Domain\Medical\Entity'
                alias: Medical
            Invitation:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Invitation/Entity'
                prefix: 'App\Domain\Invitation\Entity'
                alias: Invitation
            Course:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Course/Entity'
                prefix: 'App\Domain\Course\Entity'
                alias: Course
            Payment:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Payment/Entity'
                prefix: 'App\Domain\Payment\Entity'
                alias: Payment
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
