# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    medical_certificates_directory: '%kernel.project_dir%/var/uploads/medical_certificates'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # DDD Repository Binding: Interface -> Implementazione
    # Quando viene richiesta l'interfaccia, Symfony inietta l'implementazione Doctrine
    App\Domain\Membership\Repository\MembershipRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineMembershipRepository

    App\Domain\Membership\Repository\MembershipRequestRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineMembershipRequestRepository

    App\Domain\Membership\Repository\SubscriptionPlanRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineSubscriptionPlanRepository

    App\Domain\Membership\Repository\EnrollmentRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineEnrollmentRepository

    # Course Repositories
    App\Domain\Course\Repository\CourseRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCourseRepository

    App\Domain\Course\Repository\CourseScheduleRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCourseScheduleRepository

    App\Domain\Course\Repository\CourseEnrollmentRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCourseEnrollmentRepository

    App\Domain\Course\Repository\CourseCategoryRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCourseCategoryRepository

    App\Domain\Course\Repository\CourseWaitingListRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCourseWaitingListRepository

    App\Domain\Course\Repository\CourseSessionRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineCourseSessionRepository

    # Trainer Repositories
    App\Domain\PersonalTrainer\Repository\TrainerRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineTrainerRepository

    App\Domain\PersonalTrainer\Repository\PTClientRelationRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrinePTClientRelationRepository

    # Medical Repositories
    App\Domain\Medical\Repository\MedicalCertificateRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineMedicalCertificateRepository

    # Invitation Repositories
    App\Domain\Invitation\Repository\InvitationRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineInvitationRepository

    App\Domain\Invitation\Repository\PTClientInvitationRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrinePTClientInvitationRepository

    # User Repositories
    App\Domain\User\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository

    # Gym Repositories
    App\Domain\Gym\Repository\GymRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineGymRepository

    App\Domain\Gym\Repository\GymAttendanceRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineGymAttendanceRepository

    App\Domain\Gym\Repository\GymSettingsRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineGymSettingsRepository

    # Workout Repositories
    App\Domain\Workout\Repository\WorkoutPlanRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineWorkoutPlanRepository

    App\Domain\Workout\Repository\ClientAssessmentRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineClientAssessmentRepository

    App\Domain\Workout\Repository\ExerciseRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineExerciseRepository

    App\Domain\Workout\Repository\WorkoutExerciseRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineWorkoutExerciseRepository

    App\Domain\Workout\Repository\WorkoutSessionRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrineWorkoutSessionRepository

    # Payment Repositories
    App\Domain\Payment\Repository\PaymentRepositoryInterface:
        alias: App\Infrastructure\Persistence\Doctrine\Repository\DoctrinePaymentRepository

    # API Platform State Processors
    App\Domain\User\State\UserPasswordHasher:
        decorates: 'api_platform.doctrine.orm.state.persist_processor'
        arguments:
            $processor: '@App\Domain\User\State\UserPasswordHasher.inner'
        decoration_priority: 10

    App\Domain\Workout\State\WorkoutPlanProcessor:
        decorates: 'App\Domain\User\State\UserPasswordHasher'
        arguments:
            $processor: '@App\Domain\Workout\State\WorkoutPlanProcessor.inner'

    App\Domain\Membership\State\GymMembershipProcessor:
        decorates: 'App\Domain\Workout\State\WorkoutPlanProcessor'
        arguments:
            $processor: '@App\Domain\Membership\State\GymMembershipProcessor.inner'

    App\Domain\Invitation\State\PTClientInvitationProcessor:
        decorates: 'App\Domain\Membership\State\GymMembershipProcessor'
        arguments:
            $processor: '@App\Domain\Invitation\State\PTClientInvitationProcessor.inner'

    # File Upload Services
    App\Infrastructure\Service\FileUploadService:
        arguments:
            $uploadDirectory: '%kernel.project_dir%/var/uploads'

    App\Domain\Medical\Service\MedicalCertificateUploadService:
        arguments:
            $uploadDirectory: '%medical_certificates_directory%'
